# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edcf24fbaa28f9744030505d8e6f40b631d0bd1c03ef41fddd3382e07e9be0cd314fcf2342ee6cb5f5f3f6720442469527ae49554e30b8240f238b41cb9afb90

test:
  secret_key_base: 69ec47b5c5670c0a760640137400fd1de3eda0fe1cf6cc97754048976dc660f1e6ba4f2689b09d1b618909721c2ede2c59f3f719e190b0ea5644a67a30228817

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
